Revert "[media] rc: ir-sharp-decoder: Add encode capability"
This reverts commit 609e640b74e964a19322f26e5fc097e5c432565a.

Log:
../drivers/media/rc/ir-sharp-decoder.c:178:39: error: variable has incomplete type 'const struct ir_raw_timings_pd'
  178 | static const struct ir_raw_timings_pd ir_sharp_timings = {
      |                                       ^
../drivers/media/rc/ir-sharp-decoder.c:178:21: note: forward declaration of 'struct ir_raw_timings_pd'
  178 | static const struct ir_raw_timings_pd ir_sharp_timings = {
      |                     ^
../drivers/media/rc/ir-sharp-decoder.c:230:3: error: field designator 'encode' does not refer to any field in type 'struct ir_raw_handler'; did you mean 'decode'?
  230 |         .encode         = ir_sharp_encode,
      |          ^~~~~~
      |          decode
../drivers/media/rc/rc-core-priv.h:29:8: note: 'decode' declared here
   29 |         int (*decode)(struct rc_dev *dev, struct ir_raw_event event);
      |               ^
../drivers/media/rc/ir-sharp-decoder.c:230:13: error: incompatible function pointer types initializing 'int (*)(struct rc_dev *, struct ir_raw_event)' with an expression of type 'int (enum rc_type, u32, struct ir_raw_event *, unsigned int)' (aka 'int (enum rc_type, unsigned int, struct ir_raw_event *, unsigned int)') [-Wincompatible-function-pointer-types]
  230 |         .encode         = ir_sharp_encode,
      |                           ^~~~~~~~~~~~~~~
3 errors generated.

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: I6a255e878c8eddb352b2b0438165d9a98eb702f0