UPSTREAM: security,selinux,smack: kill security_task_wait hook
As reported by yangshukui, a permission denial from security_task_wait()
can lead to a soft lockup in zap_pid_ns_processes() since it only expects
sys_wait4() to return 0 or -ECHILD. Further, security_task_wait() can
in general lead to zombies; in the absence of some way to automatically
reparent a child process upon a denial, the hook is not useful.  Remove
the security hook and its implementations in SELinux and Smack.  Smack
already removed its check from its hook.

log:
../security/selinux/hooks.c:4066:30: error: too few arguments to function call, expected 6, have 5
PROCESS__SIGCHLD, NULL);
^
../security/selinux/include/avc.h:150:5: note: 'avc_has_perm' declared here
int avc_has_perm(struct selinux_state *state,
^
1 error generated.

Reported-by: yangshukui <yangshukui@huawei.com>
Signed-off-by: Stephen Smalley <sds@tycho.nsa.gov>
Change-Id: I3358017587aa45dce25079098c40b9a616846d2c
Acked-by: Casey Schaufler <casey@schaufler-ca.com>
Acked-by: Oleg Nesterov <oleg@redhat.com>
Signed-off-by: Paul Moore <paul@paul-moore.com>

(cherry picked from commit 3a2f5a59a695a73e0cde9a61e0feae5fa730e936)
Bug: 140252993
Signed-off-by: Jeff Vander Stoep <jeffv@google.com>
Signed-off-by: Rapherion Rollerscaperers <rapherion@raphielgang.org>
Signed-off-by: Chenyang Zhong <zhongcy95@gmail.com>
Signed-off-by: TogoFire <togofire@mailfence.com>