ASoC: wcd_cpe_core: Fix uninitialized header usage
When the cmi header is filled, it isn't zeroed out; it's updated, so the
previous value it contains is retained as part of a bitmask. This
constitutes uninitialized usage of the cmi header struct.

Fix it by zeroing out the header with a memset, as is done elsewhere in
this driver.

This fixes the following warnings:
In file included from sound/soc/codecs/wcd_cpe_core.c:27:
sound/soc/codecs/wcd_cpe_core.c: In function 'wcd_cpe_lsm_lab_control':
include/sound/cpe_cmi.h:173:18: error: 'cpe_lab_enable.hdr_info' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  173 |   CMI_HDR_SET(hdr->hdr_info, SESSION_ID_MASK,\
      |                  ^~
sound/soc/codecs/wcd_cpe_core.c: In function 'wcd_cpe_lab_ch_setup':
include/sound/cpe_cmi.h:173:18: error: 'lab_eob.hdr_info' may be used uninitialized in this function [-Werror=maybe-uninitialized]

Signed-off-by: Sultan Alsawaf <sultan@kerneltoast.com>
Signed-off-by: Lau <laststandrighthere@gmail.com>