adjust function definitions to avoid clang 16 warnings
Fix build

Error:
-use of undeclared identifier 'extra_size'
-a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]

Change-Id: 05edd258a1a1cebe1ba55b57cd251c2ba7640769
Signed-off-by: TogoFire <italomellopereira@gmail.com>