mm: vmscan: fix implicit declaration of function
Revert "mm/vmscan.c: don't round up scan size for online memory cgroup"
This reverts commit 4abebcfc723692a67bcb2156edc7ddac3881169f.

Log:
../mm/vmscan.c:2378:32: error: implicit declaration of function 'DIV64_U64_ROUND_UP'; did you mean 'DIV_ROUND_UP'? [-Werror=implicit-function-declaration]
 2378 |                                DIV64_U64_ROUND_UP(scan * fraction[file],
      |                                ^~~~~~~~~~~~~~~~~~
      |                                DIV_ROUND_UP

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: Ia1ddac93ab65e0abfdca72501f4b977b18802ad4