driver core: add devm_device_add_group() and friends
Many drivers create additional driver-specific device attributes when
binding to the device, and providing managed version of
device_create_group() will simplify unbinding and error handling in probe
path for such drivers.

Without managed version driver writers either have to mix manual and
managed resources, which is prone to errors, or open-code this function by
providing a wrapper to device_add_group() and use it with devm_add_action()
or devm_add_action_or_reset().

log: ../drivers/hid/hid-playstation.c:1288:8: error: implicit declaration of function 'devm_device_add_group' [-Werror,-Wimplicit-function-declaration]
        ret = devm_device_add_group(&hdev->dev, &ps_device_attribute_group);

Change-Id: 6036b309c335b2fbed6325686f854e47d68c03c4
Signed-off-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: TogoFire <italomellopereira@gmail.com>