timer: Prepare to change timer callback argument type
Modern kernel callback systems pass the structure associated with a
given callback to the callback function. The timer callback remains one
of the legacy cases where an arbitrary unsigned long argument continues
to be passed as the callback argument. This has several problems:

- This bloats the timer_list structure with a normally redundant
  .data field.

- No type checking is being performed, forcing callbacks to do
  explicit type casts of the unsigned long argument into the object
  that was passed, rather than using container_of(), as done in most
  of the other callback infrastructure.

- Neighboring buffer overflows can overwrite both the .function and
  the .data field, providing attackers with a way to elevate from a buffer
  overflow into a simplistic ROP-like mechanism that allows calling
  arbitrary functions with a controlled first argument.

- For future Control Flow Integrity work, this creates a unique function
  prototype for timer callbacks, instead of allowing them to continue to
  be clustered with other void functions that take a single unsigned long
  argument.

This adds a new timer initialization API, which will ultimately replace
the existing setup_timer(), setup_{deferrable,pinned,etc}_timer() family,
named timer_setup() (to mirror hrtimer_setup(), making instances of its
use much easier to grep for).

In order to support the migration of existing timers into the new
callback arguments, timer_setup() casts its arguments to the existing
legacy types, and explicitly passes the timer pointer as the legacy
data argument. Once all setup_*timer() callers have been replaced with
timer_setup(), the casts can be removed, and the data argument can be
dropped with the timer expiration code changed to just pass the timer
to the callback directly.

Since the regular pattern of using container_of() during local variable
declaration repeats the need for the variable type declaration
to be included, this adds a helper modeled after other from_*()
helpers that wrap container_of(), named from_timer(). This helper uses
typeof(*variable), removing the type redundancy and minimizing the need
for line wraps in forthcoming conversions from "unsigned data long" to
"struct timer_list *" in the timer callbacks:

-void callback(unsigned long data)
+void callback(struct timer_list *t)
{
-   struct some_data_structure *local = (struct some_data_structure *)data;
+   struct some_data_structure *local = from_timer(local, t, timer);

Finally, in order to support the handful of timer users that perform
open-coded assignments of the .function (and .data) fields, provide
cast macros (TIMER_FUNC_TYPE and TIMER_DATA_TYPE) that can be used
temporarily. Once conversion has been completed, these can be globally
trivially removed.

-log:
../kernel/sched/psi.c:208:2: error: implicit declaration of function 'timer_setup' [-Werror,-Wimplicit-function-declaration]
        timer_setup(&group->poll_timer, poll_timer_fn, 0);
        ^
../kernel/sched/psi.c:652:28: error: implicit declaration of function 'from_timer' [-Werror,-Wimplicit-function-declaration]
        struct psi_group *group = from_timer(group, t, poll_timer);
                                  ^
../kernel/sched/psi.c:652:28: note: did you mean 'mod_timer'?
../include/linux/timer.h:186:12: note: 'mod_timer' declared here
extern int mod_timer(struct timer_list *timer, unsigned long expires);
           ^
../kernel/sched/psi.c:652:49: error: use of undeclared identifier 'poll_timer'
        struct psi_group *group = from_timer(group, t, poll_timer);

This fix build to commit: psi: eliminate kthread_worker from psi trigger scheduling mechanism

Change-Id: ee718a6b75226518420607839114869fd918d159
Signed-off-by: Kees Cook <keescook@chromium.org>
Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
Link: https://lkml.kernel.org/r/20170928133817.GA113410@beast
Signed-off-by: DennySPB <dennyspb@gmail.com>
Signed-off-by: TogoFire <italomellopereira@gmail.com>